[package]
name = "sqlx-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
qorm = { git = "https://github.com/QTILabs/qorm.git" }
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite" ] }
tokio = { version = "1", features = ["full"] }
